MallBeaconWebApp/MallBeaconWebApp.Web/Controllers/AdminMasterController.cs
using MallBeaconWebApp.Core.DbClass.Admin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MallBeaconWebApp.Web.Models;
using MallBeaconWebApp.Core.DbTblViews.Admin;
using MallBeaconWebApp.Core.DbProperties.Admin;
using System.IO;

namespace MallBeaconWebApp.Web.Controllers
{
    [SessionHandler(true)]
    public class AdminMasterController : Controller
    {
        public MasterDb masterDb;

        public AdminMasterController()
        {
            masterDb = new MasterDb(SessionHandler.conStr);
        }

        // GET: AdminMaster
        public ActionResult Index()
        {
            return View();
        }

        #region shop type category actions
        public ActionResult ShopTypeCategoryList()
        {
            var model = new ShopTypeCategoryMasterView();
            try
            {
                model = masterDb.ShopTypeCategoryList();
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while getting shop type category list";
            }
            return View("~/Views/AdminMaster/ShopTypeCategory/ShopTypeCategoryList.cshtml", model);
        }

        public ActionResult AddShopTypeCategory()
        {
            var model = new ShopTypeCategoryMaster();
            try
            {
                var result = masterDb.getPreCategory("","");
                model.CategoryList = result.CategoryList;
                model.DisplayTypeList = result.DisplayTypeList;
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while getting shop type category list";
            }
            return View("~/Views/AdminMaster/ShopTypeCategory/ShopTypeCategoryView.cshtml",model);
        }

        public ActionResult UpdateShopTypeCategory(string shopTypeId)
        {
            try
            {
                if (!string.IsNullOrEmpty(shopTypeId))
                {
                    var result = masterDb.GetShopTypeCategoryDetails(shopTypeId);
                    if (result != null)
                    {
                        return View("~/Views/AdminMaster/ShopTypeCategory/ShopTypeCategoryView.cshtml", result);
                    }
                    else
                    {
                        TempData["Error"] = "Shop type category not found";
                    }
                }
                else
                {
                    TempData["Error"] = "Something went wrong";
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while getting shop type category";
            }
            return RedirectToAction("ShopTypeCategoryList");
        }

        [HttpPost]
        public ActionResult AddEditShopTypeCategory(ShopTypeCategoryMaster input, HttpPostedFileBase Logo)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if(input.ParentCategoryID > 0)
                    {
                        input.DisplayType = "";
                    }
                    if (input.ID > 0)
                    {
                        var oldLogo = Server.MapPath("~/Upload_Files/Category/") + input.CategoryLogo;
                        if (Logo != null)
                            input.CategoryLogo = Logo.FileName;
                        var result = masterDb.UpdateShopTypeCategory(input);
                        if (result)
                        {
                            //Add new photo
                            if (Logo != null)
                            {
                                //Remove old photo
                                var oldPhotoPath = oldLogo;
                                if (System.IO.File.Exists(oldPhotoPath))
                                {
                                    System.IO.File.Delete(oldPhotoPath);
                                }
                                var InputFileName = Path.GetFileName(Logo.FileName);
                                var ServerSavePath = Path.Combine(Server.MapPath("~/Upload_Files/Category/") + InputFileName);
                                //Save file to server folder  
                                Logo.SaveAs(ServerSavePath);
                            }
                            TempData["Success"] = "Shop type category updated successfully";
                        }
                        else
                        {
                            TempData["Error"] = "Failed to update shop type category";
                        }
                    }
                    else
                    {
                        if (Logo != null)
                        {
                            var InputFileName = Path.GetFileName(Logo.FileName);
                            var ServerSavePath = Path.Combine(Server.MapPath("~/Upload_Files/Category/") + InputFileName);
                            //Save file to server folder  
                            Logo.SaveAs(ServerSavePath);
                            input.CategoryLogo = InputFileName;
                        }
                        var result = masterDb.CreateShopTypeCategory(input);
                        if (result)
                        {
                            TempData["Success"] = "Shop type category added sucessfully";
                        }
                        else
                        {
                            TempData["Error"] = "Failed To add shop type category";
                        }
                    }
                }
                else
                {
                    var result = masterDb.getPreCategory(input.ParentCategoryID.ToString(),input.DisplayType);
                    input.CategoryList = result.CategoryList;
                    input.DisplayTypeList = result.DisplayTypeList;
                    return View("~/Views/AdminMaster/ShopTypeCategory/ShopTypeCategoryView.cshtml", input);
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while adding shop type category";
            }
            return RedirectToAction("ShopTypeCategoryList");
        }

        public ActionResult DeleteShopTypeCategory(string shopTypeId)
        {
            return View();
        }
        #endregion


        #region Amenity actions
        public ActionResult AmenityList()
        {
            var model = new AmenityMasterView();
            try
            {
                model = masterDb.AmenityList();
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while getting amenity list";
            }
            return View("~/Views/AdminMaster/Amenity/AmenityList.cshtml", model);
        }

        public ActionResult AddAmenity()
        {
            return View("~/Views/AdminMaster/Amenity/AmenityView.cshtml");
        }

        public ActionResult UpdateAmenity(string amenityId)
        {
            try
            {
                if (!string.IsNullOrEmpty(amenityId))
                {
                    var result = masterDb.GetAmenityDetails(amenityId);
                    if (result != null)
                    {
                        return View("~/Views/AdminMaster/Amenity/AmenityView.cshtml", result);
                    }
                    else
                    {
                        TempData["Error"] = "Amenity not found";
                    }
                }
                else
                {
                    TempData["Error"] = "Something went wrong";
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while getting amenity";
            }
            return RedirectToAction("AmenityList");
        }

        [HttpPost]
        public ActionResult AddEditAmenity(AmenityMaster input)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (input.ID > 0)
                    {
                        var result = masterDb.UpdateAmenity(input);
                        if (result)
                        {
                            TempData["Success"] = "Amenity updated successfully";
                        }
                        else
                        {
                            TempData["Error"] = "Failed to update amenity";
                        }
                    }
                    else
                    {
                        var result = masterDb.CreateAmenity(input);
                        if (result)
                        {
                            TempData["Success"] = "Amenity added sucessfully";
                        }
                        else
                        {
                            TempData["Error"] = "Failed To add amenity";
                        }
                    }
                }
                else
                {
                    return View("~/Views/AdminMaster/Amenity/AmenityView.cshtml", input);
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while adding amenity";
            }
            return RedirectToAction("AmenityList");
        }

        public ActionResult DeleteAmenity(string amenityId)
        {
            return View();
        }
        #endregion


        #region Beacon actions
        public ActionResult BeaconList()
        {
            var model = new BeaconMasterView();
            try
            {
                model = masterDb.BeaconList();
            }
            catch (Exception ex)
            {
                TempData["Error"] = "An error occured while getting beacon list";
            }

MallBeaconWebApp/MallBeaconWebApp.Web/Views/AdminMaster/Currency/CurrencyList.cshtml
@model MallBeaconWebApp.Core.DbTblViews.Admin.CurrencyMasterView
@{
    ViewBag.Title = "CurrencyList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box d-flex align-items-center justify-content-between">
                            <h4 class="mb-0 font-size-18">CURRENCY LIST</h4>
                            <div class="page-title-right">
                                <a href="@Url.Action("AddCurrency","AdminMaster")" class="btn btn-primary" style="float:right;"><i class="fa fa-plus"></i> Add New Currency</a>
                            </div>
                        </div>
                    </div>
                </div>

                @if (Model != null)
                {
                    <table id="datatable" class="table table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                        <thead class="table-dark">
                            <tr>
                                <th>SRNO</th>
                                <th>Currency Name</th>
                                <th>Currency Short Name</th>
                                <th>Currency Symbol</th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.CurrencyMasterList != null && Model.CurrencyMasterList.Count > 0)
                            {
                                for (var a = 0; a < Model.CurrencyMasterList.Count; a++)
                                {
                                    <tr>
                                        <td>@(a + 1)</td>
                                        <td>@Model.CurrencyMasterList[a].Name</td>
                                        <td>@Model.CurrencyMasterList[a].ShortName</td>
                                        <td>@Model.CurrencyMasterList[a].Symbol</td>
                                        <td><a href="@Url.Action("UpdateCurrency", "AdminMaster", new { currencyId = Model.CurrencyMasterList[a].ID })"><i class="fa fa-pencil-alt" style="color:green;"></i></a></td>
                                        <td><a href="@Url.Action("DeleteCurrency", "AdminMaster", new { currencyId = Model.CurrencyMasterList[a].ID })"><i class="fa fa-trash" style="color:red;"></i></a></td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="4">
                                        No Record Found.
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }

            </div>
        </div>
    </div>
</div>

MallBeaconWebApp/MallBeaconWebApp.Web/Views/AdminMaster/Currency/CurrencyView.cshtml
@model MallBeaconWebApp.Core.DbProperties.Admin.CurrencyMaster
@{
    ViewBag.Title = "CurrencyView";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @if (Model != null && Model.ID > 0)
                {
                    <h3 class="card-title">UPDATE CURRENCY FORM</h3>
                }
                else
                {
                    <h3 class="card-title">ADD CURRENCY FORM</h3>
                }
                @using (Html.BeginForm("AddEditCurrency", "AdminMaster"))
                {
                    <div class="form-group row">
                        <label for="example-text-input" class="col-md-2 col-form-label">Currency Name</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(z => z.Name, new { @class = "form-control", @placeholder = "Enter Currency Name" })
                            @*@Html.ValidationMessage("Name", new { @style = "color:red;" })*@
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-text-input" class="col-md-2 col-form-label">Currency Short Name</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(z => z.ShortName, new { @class = "form-control", @placeholder = "Enter Currency Short Name" })
                            @Html.ValidationMessage("ShortName", new { @style = "color:red;" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="example-text-input" class="col-md-2 col-form-label">Currency Symbol</label>
                        <div class="col-md-10">
                            @Html.TextBoxFor(z => z.Symbol, new { @class = "form-control", @placeholder = "Enter Currency Symbol" })
                            @Html.ValidationMessage("Symbol", new { @style = "color:red;" })
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        @if (Model != null && Model.ID > 0)
                        {
                            @Html.HiddenFor(z => z.ID)
                            <button type="submit" class="btn btn-success col-md-1">Update</button>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-success col-md-1">Save</button>
                        }
                        <a href="@Url.Action("CurrencyList","AdminMaster")" class="btn btn-danger col-md-1">Cancel</a>
                    </div>
                }
            </div>
        </div>
    </div> <!-- end col -->
</div>