MallBeaconWebApp/MallBeaconWebApp.Web/Controllers/FranchiesController.cs
using MallBeaconWebApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MallBeaconWebApp.Web.Controllers
{
    [SessionHandler(true)]
    public class FranchiesController : Controller
    {
        // GET: Franchies
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Dashboard()
        {
            return View();
        }
    }
}

MallBeaconWebApp/MallBeaconWebApp.Web/Views/Shared/Franchies/_FranchiesLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @Html.Partial("~/Views/Shared/_title_meta.cshtml")
    @RenderSection("styles", false)
    @Html.Partial("~/Views/Shared/_head_css.cshtml")
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/form")
    <link rel="stylesheet" type="text/css" href="~/assets/libs/summernote/summernote-bs4.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap-multiselect.css">
    <style>
        #screenshot {
            position: absolute;
            /*border: 1px solid #ccc;*/
            /*background: #333;*/
            background-color: transparent;
            padding: 5px;
            display: none;
            color: #fff;
            height: 200px;
        }
    </style>
    <script>
        $(function () {
            setTimeout(function () {
                $(".msgDiv").fadeOut(1000);
            }, 5000);
            screenshotPreview();
        });

        //Below function is used for display image in small block on hover of image button
        function screenshotPreview() {
            xOffset = 10;
            yOffset = 110;
            $("a.fupimg").hover(function (e) {
                this.t = this.title;
                this.title = "";
                var c = (this.t != "") ? "<br/>" + this.t : "";
                $("body").append("<p id='screenshot'><img src='" + this.rel + "' alt='url preview'  style='height:200px;width:auto;border: 1px solid #ccc;' />" + c + "</p>");
                $("#screenshot")
                    .css("top", (e.pageY - xOffset) + "px")
                    .css("right", (e.pageX - (e.pageX - yOffset)) + "px")
                    .fadeIn("fast");
            }, function () {
                this.title = this.t;
                $("#screenshot").remove();
            });
        }
    </script>
</head>
<body data-sidebar="dark">
    <!-- Begin page -->
    <div id="layout-wrapper">
        @Html.Partial("~/Views/Shared/_topbar.cshtml")
        @Html.Partial("~/Views/Shared/Franchies/_sidebarFranchies.cshtml")
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">
            <div class="page-content">
                <div class="container-fluid">
                    @if (TempData["SuccessMessage"] != null)
                    {
                        <div class="alert alert-success alert-dismissible fade show msgDiv" role="alert">
                            <i class="mdi mdi-check-all mr-2"></i>
                            @TempData["SuccessMessage"]
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                    }
                    @if (TempData["ErrorMessage"] != null)
                    {
                        <div class="alert alert-danger alert-dismissible fade show msgDiv" role="alert">
                            <i class="mdi mdi-block-helper mr-2"></i>
                            @TempData["ErrorMessage"]
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                    }
                    @*@Html.Partial("~/Views/Shared/_page_title.cshtml")*@

                    @RenderBody()
                </div> <!-- container-fluid -->
            </div>
            <!-- End Page-content -->

            @Html.Partial("~/Views/Shared/_footer.cshtml")
        </div>
        <!-- end main content-->
    </div>
    @RenderSection("externalhtml", required: false)
    <!-- END layout-wrapper -->
    @*@Html.Partial("~/Views/Shared/_right_sidebar.cshtml")*@
    @Html.Partial("~/Views/Shared/_vendor_scripts.cshtml")
    <!-- Form controls -->
    @Scripts.Render("~/bundles/form")
    <!-- Datatable js -->
    @Scripts.Render("~/bundles/datatable")
    <script src="~/assets/libs/summernote/summernote-bs4.min.js"></script>
    <script src="~/assets/js/bootstrap-multiselect.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

MallBeaconWebApp/MallBeaconWebApp.Web/Views/Shared/Franchies/_sidebarFranchies.cshtml
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">
    <div data-simplebar class="h-100">
        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title">Menu</li>
                <li>
                    <a href="@Url.Action("Dashboard","Franchies")" class="waves-effect">
                        <i class="bx bxs-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->